name = input("Wie heißt du?")
geburtsdatum = input("Wann wurdest du geboren?")
telefonnummer = input("Wie lautet deinen Telefonnummer?")
adresse = input("Wo wohnst du?")
print(f"Name: {name}")
print(f"Gebutsdatum: {geburtsdatum}")
print(f"Adresse: {adresse}")
korrekt = input("Sind alle Eingaben korrekt?")