[0,1,2] * 2                     # [0,1,2,0,1,2]
3 * [True,False]                # [True,False,True,False,True,False]
[1,1] + [2,2] + [3,3]           # [1,1,2,2,3,3]
["Hallo"] + ["Python",'!']      # ["Hallo","Python",'!']
2 * ([True] + [True, False])    # [True, True, False, True, True, False]